### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Helloxddd** [Michael-J-Scofield/discord-anti-spam#10]
C:\Users\MyPC\Desktop\New folder\bot.js:15
  maxDuplicatesWarning = 20; // Maximum amount of duplicate messages a user can
send in a timespan before getting warned
                           ^

SyntaxError: Unexpected token ;
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)

The Error

**Comment by Kildeon** [comment]
It's just a syntaxe error, try:
`antispam(client, { 
  warnBuffer: 3, 
  maxBuffer: 5, 
  interval: 1000,
  warningMessage: "stop spamming or I'll whack your head off.", 
  banMessage: "has been banned for spamming, anyone else?", 
  maxDuplicatesWarning: 7,
  maxDuplicatesBan: 10 
});`
