### ISSUE TITLE
Invalid shorthand property initializer

### ISSUE THREAD

**Issue by ETLegacyy** [Michael-J-Scofield/discord-anti-spam#11]
c:\Users\etleg\Desktop\Bots\TrinityAlpha\bot.js:61
	maxDuplicatesWarning = 7,
	^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by Michael-J-Scofield** [comment]
Has been fixed in the readme
