### ISSUE TITLE
DiscordAPIError: Unknown Message 

### ISSUE THREAD

**Issue by L3g3nd4ryD3v** [Michael-J-Scofield/discord-anti-spam#131]
Hey,
so I'm getting the error:

UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at RequestHandler.execute (C:\Users\Boss\Documents\Arc-Tecture\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\Boss\Documents\Arc-Tecture\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async MessageManager.delete (C:\Users\Boss\Documents\Arc-Tecture\node_modules\discord.js\src\managers\MessageManager.js:126:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

on the latest version of anti-spam.
This happens when deleting spam and on mute/kick/ban, which means this error message is produced multiple times. Also, even with removeMessages set to false they are still getting removed.
When looking at the Issue from DangoTV, setting verbose to false won't fix the problem.

I hope you can do something with this, thanks for your time.

**Comment by Scraayp** [comment]
The issue will be fixed after i merge 2.5.2
