### ISSUE TITLE
antispam is not defined, bot is not either

### ISSUE THREAD

**Issue by RyanLabaeye** [Michael-J-Scofield/discord-anti-spam#14]
Hello there
I tried editing your code a bit so that it mutes users instead of banning them,
but I can't even test it because I get these errors : 
ReferenceError: antispam is not defined
    at Object.<anonymous> (C:\Users\PC\Desktop\stuff\Bot_Discord\NodeJs\bot.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

This one is when I don't touch anything, but when I modify the function and call it anti_spam, I get this error:
ReferenceError: bot is not defined
    at Object.<anonymous> (C:\Users\PC\Desktop\stuff\Bot_Discord\NodeJs\bot.js:14:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

So I guess I have to define bot now, unless I did the wrong thing with the antispam function,
But since I'm a real newbie I don't quite know how to define that bot, I should have to give it my bot's Id or something, but I dunno.

Could you please help me ?
Thanks

**Comment by RyanLabaeye** [comment]
Just had to rename a few things
