### ISSUE TITLE
BitField Error

### ISSUE THREAD

**Issue by Kief5555** [Michael-J-Scofield/discord-anti-spam#141]
Hi,

I got this error when someone triggered the anti-spam warn/mute

/home/runner/SKSCBOT/node_modules/discord.js/src/util/BitField.js:152
    throw new RangeError('BITFIELD_INVALID', bit);
          ^

RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: ADMINSTRATOR.
    at Function.resolve (/home/runner/SKSCBOT/node_modules/discord.js/src/util/BitField.js:152:11)
    at Permissions.has (/home/runner/SKSCBOT/node_modules/discord.js/src/util/BitField.js:44:28)
    at Permissions.has (/home/runner/SKSCBOT/node_modules/discord.js/src/util/Permissions.js:54:85)
    at /home/runner/SKSCBOT/node_modules/discord-anti-spam/index.js:497:74
    at Array.some (<anonymous>)
    at AntiSpamClient.message (/home/runner/SKSCBOT/node_modules/discord-anti-spam/index.js:497:34)
    at Client.<anonymous> (/home/runner/SKSCBOT/events/anti-spam.js:27:50)
    at Client.emit (node:events:406:35)
    at MessageCreateAction.handle (/home/runner/SKSCBOT/node_modules/discord.js/src/client/actions/MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/SKSCBOT/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/SKSCBOT/node_modules/discord.js/src/client/websocket/WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (/home/runner/SKSCBOT/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/runner/SKSCBOT/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/runner/SKSCBOT/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/runner/SKSCBOT/node_modules/ws/lib/websocket.js:978:20) {
  [Symbol(code)]: 'BITFIELD_INVALID'
}

**Comment by Kief5555** [comment]
version 2.5.8 (latest btw)

**Comment by Scraayp** [comment]
It's ADMINISTRATOR. not ADMINSTRATOR

**Comment by Kief5555** [comment]
Oh, sorry I am dumb. Thanks
