### ISSUE TITLE
I am getting ussye

### ISSUE THREAD

**Issue by GangGamerAK** [Michael-J-Scofield/discord-anti-spam#3]
`C:\Users\GangGamerAK\Desktop\Genbot\okay.js:16
    maxDuplicatesWarning = 7, // Maximum amount of duplicate messages a user can send in a timespan before getting warned
    ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3` Help please

**Comment by olvrb** [comment]
remove maxDuplicatesWarning and maxDuplicatesBan for a temporary fix

**Comment by Michael-J-Scofield** [comment]
Replace = with : typo in my docs
