### ISSUE TITLE
client.on error

### ISSUE THREAD

**Issue by tabamodz** [Michael-J-Scofield/discord-anti-spam#34]
im getting an error
PS D:\Downloads\DiscordBot> node .
D:\Downloads\DiscordBot\index.js:5
client.on('ready', () => {
^

ReferenceError: client is not defined
    at Object.<anonymous> (D:\Downloads\DiscordBot\index.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
PS D:\Downloads\DiscordBot>
?? how do I fix

**Comment by rozivector** [comment]
You need define the client first: 
```javascript
const Discord = require('discord.js');
const client = new Discord.Client();
```

**Comment by MrAugu** [comment]
`client` variable is assumed to be the variable that defines your `new Discord.Client()`
